import { typecheck } from './typecheck.mjs'
import fastGlob from 'fast-glob'
import esbuild from 'esbuild'
import process from 'process'
import path from 'path'
import os from 'os'
import fs from 'fs'

const outdir = './out/bike'

console.log(`Building to directory: ${outdir}\n`)

fs.mkdirSync(outdir, { recursive: true })
fs.copyFileSync('./src/!app/sheet.html', path.join(outdir, 'sheet.html'))
fs.copyFileSync('./src/!app/inspector.html', path.join(outdir, 'inspector.html'))

const prod = process.argv[2] === 'production'
const context = await esbuild.context({
  banner: { js: '// GENERATED BY ESBUILD' },
  target: 'esnext',
  entryPoints: ['./src/!app/bike', './src/!app/sheet', './src/!app/inspector'],
  external: ['@dom'],
  format: 'iife',
  globalName: 'Bike',
  logLevel: 'info',
  //sourcemap: prod ? 'external' : 'inline',
  outdir: outdir,
  bundle: true,
  minify: prod,
  keepNames: true,
})

if (prod) {
  await context.rebuild()
  process.exit(0)
} else {
  await context.watch()
}
